# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46ab12165254d331085671cd365751b4395b4c3ec517b759a96bc254d8934ed44c1db07b950341c45bac1268fb90c7241b8e0688dca14af86025c56eec3df68b

test:
  secret_key_base: c362360359448acd5175771f4309be46c82518cbeb31b0c77a865a824f9076653e902b2e7340c8048bcefbaebd53670c9470c3625ff6096d279054e804bc4344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
